/*

* AUTHOR : Partha Chakraborty
*
* PROGRAM : Number_Guessing_Game.java
*
* DATE CREATED : 26-05-2024
*
* Description :
 "Guessing the Number" in this Java project allows the user to guess the number generated by the computer & involves the following steps:
* The system generates a random number from a given range, from 1 to 100.
* The user is prompted to enter their given number in a displayed dialogue box.
* The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
* The game continues under the user guessing the number.
* You will have 10 attempts and you will also get points according to your attempts

 */

import java.util.Random;
import java.util.Scanner;

public class Number_Guessing_Game {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

//        Initializing variables -----
        int lowerBound = 1;
        int upperBound = 100;
        int maxAttempts = 10;
        int rounds = 0;
        int score = 0;

//        Welcome interface -----
        System.out.println("-------------------------------------------------------------");
        System.out.println("           WELCOME TO THE NUMBER GUESSING GAME !!           ");
        System.out.println("         I'm Thinking Of A Number Between " + lowerBound + " And "      + upperBound);
        System.out.println("-------------------------------------------------------------");

        while (true) {
            int secretNumber = random.nextInt(upperBound - lowerBound + 1) + lowerBound;
            int attempts = 0;

            System.out.println("Round " + (rounds + 1));
            System.out.println("You Have Total " + maxAttempts + " Attempts To Guess The Number !");
            System.out.println("");
            while (attempts < maxAttempts) {
                System.out.print("Enter your guess number: ");
                int userGuess = scanner.nextInt();
                attempts++;

                if (userGuess == secretNumber) {
                    System.out.println("Congratulations!! You Guessed The Number In " + attempts + " Attempts.");
                    System.out.println("");
                    score += maxAttempts - attempts + 1;
                    break;
                } else if (userGuess < secretNumber) {
                    System.out.println("Too low.. Please try again...");
                    System.out.println("");
                } else {
                    System.out.println("Too high.. Please try again...");
                    System.out.println("");
                }
            }

            System.out.print("Do you want to play again? (yes/no): ");
            String playAgain = scanner.next();

            if (!playAgain.equalsIgnoreCase("yes")) {
                System.out.println("Game Over..Your Total Score Is " + score + " Points.");
                break;
            }

            rounds++;
        }

        scanner.close();
    }
}